server:
  port: 8081
spring:
  application:
    name: pdf-epub-service
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 1000MB

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://misaki.center:3306/conveter?useUnicode=true&characterSet=utf-8
      username: root
      password: WSY20030112
  jpa:
    database: mysql
    show-sql: true  #展示SQL语句
    generate-ddl: true  #是否自动建表
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect

com:
  path:
    EpubPath: D:\data\pdf\Test\EpubTotal
    PdfPath: D:\data\pdf\Test\PdfTotal
    HtmlPath: D:\data\pdf\Test\HtmlTotal

#eureka的配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7081/eureka/
  instance:
    instance-id: pdf_epub_Provider8081



