server:
  port: 7081

#Eureka的配置
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false        #为false表示自己是注册中心
    register-with-eureka: false  #表示是否向eureka注册中心注册自己
    service-url:
      defaultZone: http://localhost:7081/eureka/
