server:
  port: 9527
spring:
  application:
    name: conveter-system-zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7081/eureka/
  instance:
    instance-id: zuul-9527
    prefer-ip-address: true

zuul:
  routes:
    first.serviceId: pdf-epub-service
    first.path: /first/**
  ignored-services: pdf-epub-service
